on:
  push:
  workflow_dispatch:
jobs:
  prepare_env:
    runs-on: ubuntu-latest
    name: job name
    steps:
      - name: First step
        run: |
          echo $(pwd)
          echo $(whoami)
          echo $(ls -la)
          echo $(mkdir test123)
          
      - uses: actions/checkout@v3
      
#       - name: install poetry
#         run: |
#          pip3 install poetry
          
      - name: Python bump version
        id: hello
        uses: Sean-Wu-HV/my-action@poetry
        with:
          version: '1.1.1'
      
      - name: Python bump version
        id: my-action
        uses: Sean-Wu-HV/my-action@master
        with:
          help-option: 'idk'
          test-option: 'idk either'
          
#       - name: Commit and push changes
#         run: |
#           git config --global user.name "Sean-Wu-HV"
#           git config --global user.email "sean840411@gmail.com"

#           git add -A
#           git commit -m "new change"
#           git push https://Sean-Wu-HV:${GH_TOKEN}@github.com/Sean-Wu-HV/use-my-action2.git

        
