on:
  push:
  workflow_dispatch:
jobs:
  prepare_env:
    runs-on: ubuntu-latest
    name: job name
    steps:
      - name: First step
        run: |
          echo $(pwd)
          echo $(whoami)
          echo $(ls -la)
          echo $(mkdir test123)
          
      - uses: actions/checkout@v3
          
      - name: Python bump version
        id: hello
        uses: Sean-Wu-HV/my-action@poetry
#         with:
#           input-args: '-h'
        
