on:
  push:
  workflow_dispatch:
jobs:
  prepare_env:
    runs-on: ubuntu-latest
    name: job name
    steps:
      - name: First step
        run: |
          echo $(pwd)
          echo $(whoami)
          echo $(ls -la)
          echo $(mkdir test123)
          
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: check dir
        run: |
          echo $(ls -la)
          
      - name: Update image tag
        run: |
            echo 'hello'
