on:
  push:
  workflow_dispatch:
jobs:
  prepare_env:
    runs-on: ubuntu-latest
    name: job name
    steps:
      - name: First step
        run: |
          echo $(pwd)
          echo $(whoami)
          echo $(ls -la)
          echo $(mkdir test123)
          
      - uses: actions/checkout@v3
      
      - name: test array
        uses: Sean-Wu-HV/use-my-action2@composite-action
        with:
          CRD_NAME: "accccc"
      

#       - name: Blackduck Scan
#         uses: addnab/docker-run-action@v3
#         with:
#           image: blackducksoftware/detect:8
#           options: --entrypoint "/bin/bash" -v $(GITHUB_WORKSPACE):/source
#           run: |
#             echo "ls -la /source $(ls -la /source)"

            
#       - name: install poetry
#         run: |
#          pip3 install poetry
          
#       - name: Python bump version
#         id: hello
#         uses: Sean-Wu-HV/my-action@poetry
#         with:
#           version: '1.1.1'
      
#       - name: Python bump version
#         id: my-action
#         uses: Sean-Wu-HV/my-action@main
#         with:
#           help-option: 'idk'
#           test-option: 'idk either'
          
#       - name: Commit and push changes
#         run: |
#           git config --global user.name "Sean-Wu-HV"
#           git config --global user.email "sean840411@gmail.com"

#           git add -A
#           git commit -m "new change"
#           git push https://Sean-Wu-HV:${GH_TOKEN}@github.com/Sean-Wu-HV/use-my-action2.git

        
